### ISSUE TITLE
Plants in my area

### ISSUE THREAD

**Issue by Mona904** [Mona904/capstone-project#1]
## Value proposition

As a user
I want to see the list of plants that can be grown in my area,
in order to purchase the best plant suitable to the climate where I live as well as my lifestyle.

## Description
![Untitled-2023-04-28-1013](https://user-images.githubusercontent.com/126586287/236130011-7b68db00-309e-4ae9-8a9d-754c3af0d6f5.png)

## Acceptance criteria

- [ ] Plants are displayed in grid form
- [ ] Plant names are displayed below each picture
- [ ] List scrolls vertically

## Tasks

- [ ] Create a branch
- [ ] Global styles
- [ ] components/ Card

Size:

**Comment by CJAkkuec** [comment]
Looking great! Really like the wireframes. 👍
