### ISSUE TITLE
Favourites Page

### ISSUE THREAD

**Issue by Mona904** [Mona904/capstone-project#2]
## Value proposition

As a plant enthusiast, I want to be able to save my favourite plants in a separate page, 
so that I can easily access them and keep track of my collection.

## Description
![Untitled-2023-04-28-1013](https://user-images.githubusercontent.com/126586287/236160221-dbe5685a-760e-436d-9ca7-bc7435c58cc0.png)
## Acceptance criteria

- [ ] The heart toggle button should be clearly visible on the plant page
- [ ] When the user clicks on the heart toggle button, the button should change to indicate that the plant has been added to their favourites list
- [ ] When the user clicks on the heart toggle button again, the button should change to indicate that the plant has been removed from their favourites list.
- [ ] The favourites page should only display the plants that the user has selected as their favourites.
- [ ] The favourites page should display the details of each plant, including its name & image.
- [ ] The user should be able to navigate back and forth between the plant page and the favourites page using a clearly visible button.
- [ ] The app should save the user's favourites list even after they close the app or log out.

## Tasks

- [ ] Create a feature branch
- [ ] Create a separate "Favourites" page for the user's selected plants
- [ ] update components/ Card
- [ ] Implement a "heart" toggle button on the plant page.
- [ ] Allow the user to add a plant to their favourites list by clicking on the heart toggle button on the plant page.
- [ ] Allow the user to remove a plant from their favourites list by clicking on the heart toggle button again.
- [ ] Ensure that the favourites page only displays the plants that the user has selected as their favourites.
- [ ] Allow the user to navigate back and forth between the plant page and the favourites page.

Size:

**Comment by mbosselmann** [comment]
Hi Mona,
you rock! 🪨 Nothing to remark from my side I only have one note:

If you do not want to set a **size** for your user story (this is optional) then you can remove this part. With your size you can decide what you think is the complexity of your user story (usually small, medium or large). 

But this does not hinder me from approving your user story. 🦊

**Comment by Mona904** [comment]
Hi Mareike, completely forgot about that aspect 😅  
Will use it in the future, thank you 😃
