### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Mona904** [Mona904/capstone-project#3]
## Value proposition

As a plant lover, I want to be able to search for plants using a search bar so that I can easily find the plants that I am interested in.

## Description
![Untitled-2023-04-280-1013](https://user-images.githubusercontent.com/126586287/236176819-802b05c9-83c5-4ed0-9955-94705263cf10.png)

## Acceptance criteria

- [ ] The search bar should be clearly visible on the main page of the app.
- [ ] The search bar should allow the user to enter any text-based search term.
- [ ] The search results should display a list of plants that match the search term entered by the user.
- [ ] Clicking on a plant from the search results should take the user to a page with more details about that plant.

## Tasks

- [ ] Implement a search bar on the main page of the app.
- [ ] Allow the user to enter a search term in the search bar.
- [ ] Display a list of plants that match the search term entered by the user.
- [ ] Allow the user to click on a plant from the search results to view more details about that plant.
- [ ] Include an option to clear the search bar to return to the original list of plants.

Size: L
